import { createSlice, PayloadAction } from '@reduxjs/toolkit';

const initailReviews = [
  {
    'restaurant name': 'Alsancak Simit Sarayi',
    'id restaurant': 111,
    'id chef': 'JC1',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Adana Grillhaus',
    'id restaurant': 112,
    'id chef': 'JC1',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Alt Berliner Wirtshaus Henne',
    'id restaurant': 113,
    'id chef': 'JC1',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Prater Beer Garden',
    'id restaurant': 114,
    'id chef': 'JC1',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Borchardt',
    'id restaurant': 115,
    'id chef': 'JC1',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Libensmittel in Mitte',
    'id restaurant': 116,
    'id chef': 'JC1',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Zollpackhof',
    'id restaurant': 117,
    'id chef': 'JC1',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Papaya',
    'id restaurant': 118,
    'id chef': 'JC1',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Thai-art',
    'id restaurant': 119,
    'id chef': 'JC1',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Kin Dee',
    'id restaurant': 120,
    'id chef': 'JC1',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Chungking Noodles',
    'id restaurant': 121,
    'id chef': 'JC1',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Smartdeli Sushi & More',
    'id restaurant': 122,
    'id chef': 'JC1',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Aroma',
    'id restaurant': 123,
    'id chef': 'JC1',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Wok Show',
    'id restaurant': 124,
    'id chef': 'JC1',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Sasaya',
    'id restaurant': 125,
    'id chef': 'JC1',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Doyum',
    'id restaurant': 126,
    'id chef': 'JC1',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': "Mustafa's Gemüse Kebap",
    'id restaurant': 127,
    'id chef': 'JC1',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Tadim',
    'id restaurant': 128,
    'id chef': 'JC1',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': "K'Ups Gemüsekebap",
    'id restaurant': 129,
    'id chef': 'JC1',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Gel Gör',
    'id restaurant': 130,
    'id chef': 'JC1',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Güllü Lamachun',
    'id restaurant': 131,
    'id chef': 'JC1',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Kumru',
    'id restaurant': 132,
    'id chef': 'JC1',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Örnek Lahmacun Evi',
    'id restaurant': 133,
    'id chef': 'JC1',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Imren Grill',
    'id restaurant': 134,
    'id chef': 'JC1',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Guten dag',
    'id restaurant': 135,
    'id chef': 'JC1',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Habibi',
    'id restaurant': 136,
    'id chef': 'JC1',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Jones',
    'id restaurant': 137,
    'id chef': 'JC1',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'RISA',
    'id restaurant': 138,
    'id chef': 'JC1',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Curry 36',
    'id restaurant': 139,
    'id chef': 'JC1',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Companion',
    'id restaurant': 140,
    'id chef': 'JC1',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Rocket & Basil',
    'id restaurant': 141,
    'id chef': 'JC1',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Bonanza Coffee Roasters',
    'id restaurant': 142,
    'id chef': 'JC1',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Sofi',
    'id restaurant': 143,
    'id chef': 'JC1',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Estelle Dining',
    'id restaurant': 144,
    'id chef': 'JC1',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Julius',
    'id restaurant': 145,
    'id chef': 'JC1',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Barra',
    'id restaurant': 146,
    'id chef': 'JC1',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'ernst',
    'id restaurant': 147,
    'id chef': 'JC1',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Lode & Stijn',
    'id restaurant': 148,
    'id chef': 'JC1',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Chung King Noodles',
    'id restaurant': 121,
    'id chef': 'DR1',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Mings',
    'id restaurant': 149,
    'id chef': 'DR1',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Lamazère Brasserie',
    'id restaurant': 150,
    'id chef': 'DR1',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Mrs. Robinsons',
    'id restaurant': 151,
    'id chef': 'DR1',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Malafemmena Schöneberg',
    'id restaurant': 152,
    'id chef': 'DR1',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Gel Gör',
    'id restaurant': 130,
    'id chef': 'DR1',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Tantris',
    'id restaurant': 211,
    'id chef': 'MG2',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Werneckhof Sigi Schelling',
    'id restaurant': 212,
    'id chef': 'MG2',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Theresa Grill',
    'id restaurant': 213,
    'id chef': 'MG2',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Chez Fritz',
    'id restaurant': 214,
    'id chef': 'MG2',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Giorgia Trattoria',
    'id restaurant': 215,
    'id chef': 'MG2',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'M’Uniqo Rooftop Bar',
    'id restaurant': 216,
    'id chef': 'MG2',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Dinatale Cafe',
    'id restaurant': 217,
    'id chef': 'MG2',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Schoko.Laden',
    'id restaurant': 218,
    'id chef': 'MG2',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Cochinchina',
    'id restaurant': 219,
    'id chef': 'MG2',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Viktualien Markt',
    'id restaurant': 220,
    'id chef': 'MG2',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Delicatessen Place',
    'id restaurant': 311,
    'id chef': 'RM3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Doyenné',
    'id restaurant': 312,
    'id chef': 'RM3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Rigmarole',
    'id restaurant': 313,
    'id chef': 'RM3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Chez Marius',
    'id restaurant': 314,
    'id chef': 'RM3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Omusubi Gonbei',
    'id restaurant': 315,
    'id chef': 'RM3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Juji-ya',
    'id restaurant': 316,
    'id chef': 'RM3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Quinsou',
    'id restaurant': 317,
    'id chef': 'RM3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Oxte',
    'id restaurant': 318,
    'id chef': 'RM3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': "L'Ambroisie",
    'id restaurant': 319,
    'id chef': 'RM3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Recoin',
    'id restaurant': 320,
    'id chef': 'RM3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': "New Saveurs d'Asie",
    'id restaurant': 321,
    'id chef': 'RM3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Shang Palace',
    'id restaurant': 322,
    'id chef': 'RM3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 323,
    'id restaurant': 323,
    'id chef': 'RM3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Lao Siam',
    'id restaurant': 324,
    'id chef': 'RM3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Baratin',
    'id restaurant': 325,
    'id chef': 'RM3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': "Sonny's Pizza",
    'id restaurant': 326,
    'id chef': 'RM3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Song Heng',
    'id restaurant': 327,
    'id chef': 'BG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Double Dragon',
    'id restaurant': 328,
    'id chef': 'BG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Grand Bol',
    'id restaurant': 329,
    'id chef': 'BG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Café des Ministères',
    'id restaurant': 330,
    'id chef': 'BG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Tempilenti',
    'id restaurant': 331,
    'id chef': 'BG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Cuties',
    'id restaurant': 332,
    'id chef': 'BG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Clarence',
    'id restaurant': 323,
    'id chef': 'BG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Bar de la Croix Rouge',
    'id restaurant': 334,
    'id chef': 'BG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Tawlet',
    'id restaurant': 335,
    'id chef': 'BG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'LiLi',
    'id restaurant': 336,
    'id chef': 'BG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Urfa Durum',
    'id restaurant': 337,
    'id chef': 'BG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Tsukizi',
    'id restaurant': 338,
    'id chef': 'BG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'La Poule au Pot',
    'id restaurant': 339,
    'id chef': 'BG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Soces',
    'id restaurant': 340,
    'id chef': 'BG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Cravan',
    'id restaurant': 341,
    'id chef': 'BG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Table',
    'id restaurant': 342,
    'id chef': 'MG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Clarence',
    'id restaurant': 323,
    'id chef': 'MG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Café les Deux Gares',
    'id restaurant': 344,
    'id chef': 'MG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Petit Célestin',
    'id restaurant': 345,
    'id chef': 'MG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Café des Ministères',
    'id restaurant': 330,
    'id chef': 'MG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Neso',
    'id restaurant': 346,
    'id chef': 'MG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Butcher of Paris',
    'id restaurant': 347,
    'id chef': 'MG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Maison',
    'id restaurant': 348,
    'id chef': 'MG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Petrelle',
    'id restaurant': 349,
    'id chef': 'MG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Passerini',
    'id restaurant': 357,
    'id chef': 'MG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': "L'Abysse au Pavillon Ledoyen - Yannick Alléno",
    'id restaurant': 350,
    'id chef': 'GS3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Sushi B',
    'id restaurant': 351,
    'id chef': 'GS3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Dumbo',
    'id restaurant': 352,
    'id chef': 'GS3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Les Enfants du Marché',
    'id restaurant': 302,
    'id chef': 'GS3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Table',
    'id restaurant': 342,
    'id chef': 'GS3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Ruisseau Burger Joint',
    'id restaurant': 353,
    'id chef': 'GS3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Clarence',
    'id restaurant': 323,
    'id chef': 'GS3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Clamato',
    'id restaurant': 354,
    'id chef': 'GS3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Clown Bar',
    'id restaurant': 355,
    'id chef': 'GS3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Arpège',
    'id restaurant': 356,
    'id chef': 'GS3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Chateaubriand',
    'id restaurant': 358,
    'id chef': 'GP3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Verre Volé',
    'id restaurant': 359,
    'id chef': 'GP3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Cadoret',
    'id restaurant': 360,
    'id chef': 'GP3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Doyenné',
    'id restaurant': 312,
    'id chef': 'GP3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Ama Siam',
    'id restaurant': 361,
    'id chef': 'GP3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Square Trousseau',
    'id restaurant': 362,
    'id chef': 'GP3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Racines',
    'id restaurant': 362,
    'id chef': 'GP3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Dilia la Cave',
    'id restaurant': 364,
    'id chef': 'GP3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Ici même',
    'id restaurant': 365,
    'id chef': 'GP3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Adar',
    'id restaurant': 366,
    'id chef': 'GP3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Chez Marius',
    'id restaurant': 314,
    'id chef': 'GP3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Chantoieseau',
    'id restaurant': 367,
    'id chef': 'EC3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Restaurant H',
    'id restaurant': 368,
    'id chef': 'EC3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Oka',
    'id restaurant': 369,
    'id chef': 'EC3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Bistrot Paul Bert',
    'id restaurant': 370,
    'id chef': 'EC3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Maison',
    'id restaurant': 348,
    'id chef': 'EC3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Frenchie Pigalle',
    'id restaurant': 372,
    'id chef': 'EC3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'El Nopal',
    'id restaurant': 373,
    'id chef': 'EC3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': "L'Assiette",
    'id restaurant': 374,
    'id chef': 'EC3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Severo',
    'id restaurant': 375,
    'id chef': 'EC3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Petrelle',
    'id restaurant': 349,
    'id chef': 'HG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Méert',
    'id restaurant': 376,
    'id chef': 'HG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Recoin',
    'id restaurant': 320,
    'id chef': 'HG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Delicatessen Place',
    'id restaurant': 311,
    'id chef': 'HG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Caviar Kaspia',
    'id restaurant': 378,
    'id chef': 'HG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Clamato',
    'id restaurant': 354,
    'id chef': 'HG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Mr. Wong',
    'id restaurant': 1001,
    'id chef': 'HG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Chat Thai',
    'id restaurant': 1002,
    'id chef': 'HG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Sixpenny',
    'id restaurant': 1003,
    'id chef': 'HG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Saint Peter',
    'id restaurant': 1004,
    'id chef': 'HG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Delicatessen Place',
    'id restaurant': 311,
    'id chef': 'AS3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Udon Bistro Kunitoraya',
    'id restaurant': 378,
    'id chef': 'AS3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Chez Aline',
    'id restaurant': 379,
    'id chef': 'AS3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Bang Bang',
    'id restaurant': 380,
    'id chef': 'AS3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Dong Huong',
    'id restaurant': 381,
    'id chef': 'AS3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Maquis',
    'id restaurant': 382,
    'id chef': 'AS3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Rigmarole',
    'id restaurant': 313,
    'id chef': 'AS3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Tempilenti',
    'id restaurant': 331,
    'id chef': 'AS3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Café les Deux Gares',
    'id restaurant': 344,
    'id chef': 'AS3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Chez Xu',
    'id restaurant': 383,
    'id chef': 'AS3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Siseng',
    'id restaurant': 384,
    'id chef': 'MS3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Plénitude - Cheval Blanc Paris',
    'id restaurant': 385,
    'id chef': 'MS3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Miznon',
    'id restaurant': 386,
    'id chef': 'MS3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'David Toutain',
    'id restaurant': 387,
    'id chef': 'MS3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Ogata',
    'id restaurant': 388,
    'id chef': 'MS3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Dumbo',
    'id restaurant': 389,
    'id chef': 'MS3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'A Mi-Chemin',
    'id restaurant': 390,
    'id chef': 'MS3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': "L'Abysse au Pavillon Ledoyen - Yannick Alléno",
    'id restaurant': 391,
    'id chef': 'MS3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Urfa Durum',
    'id restaurant': 337,
    'id chef': 'MS3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Shang Palace',
    'id restaurant': 392,
    'id chef': 'MS3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Kodawari Ramen',
    'id restaurant': 392,
    'id chef': 'MS3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Kei',
    'id restaurant': 393,
    'id chef': 'MS3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Square Trousseau',
    'id restaurant': 394,
    'id chef': 'ST3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Jin',
    'id restaurant': 395,
    'id chef': 'ST3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Okuda',
    'id restaurant': 396,
    'id chef': 'ST3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Abri Soba',
    'id restaurant': 397,
    'id chef': 'ST3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Septime',
    'id restaurant': 398,
    'id chef': 'ST3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Dauphin',
    'id restaurant': 399,
    'id chef': 'ST3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Châteaubriand',
    'id restaurant': 358,
    'id chef': 'ST3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'BAMBINO',
    'id restaurant': 400,
    'id chef': 'ST3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Relais Plaza',
    'id restaurant': 401,
    'id chef': 'ST3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Chez Aline',
    'id restaurant': 379,
    'id chef': 'ST3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Baratin',
    'id restaurant': 325,
    'id chef': 'ST3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Bougainville',
    'id restaurant': 402,
    'id chef': 'ST3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Chez Georges',
    'id restaurant': 403,
    'id chef': 'ST3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Du Pain et des Idées',
    'id restaurant': 404,
    'id chef': 'ST3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Do et Riz',
    'id restaurant': 405,
    'id chef': 'ST3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'EchizenSOBA TOGO',
    'id restaurant': 406,
    'id chef': 'ST3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Hôtel Regina',
    'id restaurant': 407,
    'id chef': 'ST3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Severo',
    'id restaurant': 375,
    'id chef': 'ST3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Ritz Bar',
    'id restaurant': 408,
    'id chef': 'ST3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Chez Aline',
    'id restaurant': 379,
    'id chef': 'TC3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Café du coin',
    'id restaurant': 409,
    'id chef': 'TC3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Chez Wang',
    'id restaurant': 410,
    'id chef': 'TC3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Banh Mi',
    'id restaurant': 411,
    'id chef': 'TC3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Table',
    'id restaurant': 342,
    'id chef': 'TC3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Clarence',
    'id restaurant': 323,
    'id chef': 'TC3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Les Enfants du Marché',
    'id restaurant': 302,
    'id chef': 'TC3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Café des Ministères',
    'id restaurant': 330,
    'id chef': 'TC3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Ngoc Xuyen Saigon',
    'id restaurant': 412,
    'id chef': 'TC3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Bar Principal',
    'id restaurant': 413,
    'id chef': 'TC3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Parcelles',
    'id restaurant': 414,
    'id chef': 'NGE3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Grande Brasserie',
    'id restaurant': 415,
    'id chef': 'NGE3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Mokonuts',
    'id restaurant': 416,
    'id chef': 'NGE3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Folderol',
    'id restaurant': 417,
    'id chef': 'NGE3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Brutos',
    'id restaurant': 418,
    'id chef': 'NGE3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Patrick Roger',
    'id restaurant': 419,
    'id chef': 'NGE3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Hexagone Café',
    'id restaurant': 420,
    'id chef': 'NGE3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Mary Céleste',
    'id restaurant': 421,
    'id chef': 'NGE3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'LE TAGINE RESTAURANT',
    'id restaurant': 422,
    'id chef': 'NGE3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Clarence',
    'id restaurant': 323,
    'id chef': 'NGE3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Restaurant Omar Dhiab',
    'id restaurant': 423,
    'id chef': 'AG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'David Toutain',
    'id restaurant': 387,
    'id chef': 'AG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Royal China',
    'id restaurant': 424,
    'id chef': 'AG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Auberge Nicolas Flamel',
    'id restaurant': 425,
    'id chef': 'AG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'PNY Burger',
    'id restaurant': 426,
    'id chef': 'AG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Street Bangkok',
    'id restaurant': 427,
    'id chef': 'AG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'L’Ambassade d’Auvergne',
    'id restaurant': 428,
    'id chef': 'AG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Restaurant LOUIS par le chef Stéphane Pitré',
    'id restaurant': 429,
    'id chef': 'AG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Magna Street Food',
    'id restaurant': 430,
    'id chef': 'AG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Mirazur',
    'id restaurant': 1005,
    'id chef': 'AG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Baratin',
    'id restaurant': 325,
    'id chef': 'MG33',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Royal China',
    'id restaurant': 424,
    'id chef': 'MG33',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Sanjo',
    'id restaurant': 431,
    'id chef': 'MG33',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Udon Bistro Kunitoraya',
    'id restaurant': 378,
    'id chef': 'MG33',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Bistrot Paul Bert',
    'id restaurant': 370,
    'id chef': 'MG33',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Palais du Grand Moghol',
    'id restaurant': 432,
    'id chef': 'MG33',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Au Petit Panisse',
    'id restaurant': 433,
    'id chef': 'MG33',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Lao Siam',
    'id restaurant': 324,
    'id chef': 'MG33',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Phở Bánh Cuốn 14',
    'id restaurant': 434,
    'id chef': 'MG33',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Clarence',
    'id restaurant': 323,
    'id chef': 'MG33',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Rubis',
    'id restaurant': 435,
    'id chef': 'MG33',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': "Le Bistrot d'a Cote Flaubert",
    'id restaurant': 436,
    'id chef': 'TM3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': "L'Épi Dupin",
    'id restaurant': 437,
    'id chef': 'TM3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Auberge de Crussol',
    'id restaurant': 438,
    'id chef': 'TM3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Maison Cachée',
    'id restaurant': 439,
    'id chef': 'TM3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': "L'Auberge De Saint Rémy",
    'id restaurant': 440,
    'id chef': 'TM3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'La Merenda',
    'id restaurant': 441,
    'id chef': 'TM3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Citta di Siena',
    'id restaurant': 442,
    'id chef': 'TM3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'La Petite Maison',
    'id restaurant': 443,
    'id chef': 'TM3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Bistro D’Hugo',
    'id restaurant': 444,
    'id chef': 'TM3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Brutos',
    'id restaurant': 418,
    'id chef': 'SM3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Lac de L’Ouest',
    'id restaurant': 445,
    'id chef': 'SM3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': "Sonny's Pizza",
    'id restaurant': 326,
    'id chef': 'SM3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Gramme',
    'id restaurant': 446,
    'id chef': 'SM3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Chez Alain Miam Miam',
    'id restaurant': 447,
    'id chef': 'SM3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Naritake Ramen',
    'id restaurant': 448,
    'id chef': 'SM3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Lao Siam',
    'id restaurant': 324,
    'id chef': 'SM3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'SiSeng',
    'id restaurant': 384,
    'id chef': 'SM3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Melt',
    'id restaurant': 449,
    'id chef': 'SM3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Udon Bistro Kunitoraya',
    'id restaurant': 378,
    'id chef': 'SM3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Baratin',
    'id restaurant': 325,
    'id chef': 'HC3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Muniyandi Vilas',
    'id restaurant': 450,
    'id chef': 'HC3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Lac de l’Ouest',
    'id restaurant': 445,
    'id chef': 'HC3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'New Hoa Khoan',
    'id restaurant': 451,
    'id chef': 'HC3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Restaurant Ella',
    'id restaurant': 452,
    'id chef': 'HC3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Bob De Tunis',
    'id restaurant': 453,
    'id chef': 'HC3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Chez Aline',
    'id restaurant': 379,
    'id chef': 'HC3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Clamato',
    'id restaurant': 354,
    'id chef': 'GM3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Langosteria',
    'id restaurant': 505,
    'id chef': 'GM3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Rubis',
    'id restaurant': 435,
    'id chef': 'GM3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Kodawari Ramen (Tsukiji)',
    'id restaurant': 506,
    'id chef': 'GM3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Petit Bao',
    'id restaurant': 507,
    'id chef': 'GM3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Grazie',
    'id restaurant': 508,
    'id chef': 'GM3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Clarence',
    'id restaurant': 323,
    'id chef': 'GM3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Rose Bakery',
    'id restaurant': 509,
    'id chef': 'GM3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Adar',
    'id restaurant': 366,
    'id chef': 'GM3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Petrelle',
    'id restaurant': 349,
    'id chef': 'CVF3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Alliance',
    'id restaurant': 611,
    'id chef': 'CVF3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Verre Volé',
    'id restaurant': 359,
    'id chef': 'CVF3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Fief',
    'id restaurant': 612,
    'id chef': 'CVF3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': "L'Assiette",
    'id restaurant': 613,
    'id chef': 'CVF3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Maison',
    'id restaurant': 348,
    'id chef': 'CVF3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Brasserie Lipp',
    'id restaurant': 614,
    'id chef': 'CVF3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Les Inséparables',
    'id restaurant': 615,
    'id chef': 'JG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': "Le Bistrot d'a Cote Flaubert",
    'id restaurant': 436,
    'id chef': 'JG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Eels',
    'id restaurant': 616,
    'id chef': 'JG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Brigade du Tigre',
    'id restaurant': 617,
    'id chef': 'JG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Auberge Nicolas Flamel',
    'id restaurant': 425,
    'id chef': 'JG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Pottoka',
    'id restaurant': 618,
    'id chef': 'JG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Restaurant Omar Dhiab',
    'id restaurant': 423,
    'id chef': 'JG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Parcelles',
    'id restaurant': 414,
    'id chef': 'JG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Royal China',
    'id restaurant': 424,
    'id chef': 'JG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Clarence',
    'id restaurant': 323,
    'id chef': 'JG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'La Réserve',
    'id restaurant': 619,
    'id chef': 'JG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Clarence',
    'id restaurant': 323,
    'id chef': 'MI3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Table',
    'id restaurant': 342,
    'id chef': 'MI3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Magma',
    'id restaurant': 620,
    'id chef': 'MI3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Parcelles',
    'id restaurant': 414,
    'id chef': 'MI3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Osteria Ferrara',
    'id restaurant': 621,
    'id chef': 'MI3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'EnYaa',
    'id restaurant': 622,
    'id chef': 'MI3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Petit Célestin',
    'id restaurant': 345,
    'id chef': 'MI3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Les Arlots',
    'id restaurant': 623,
    'id chef': 'KL3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'XiaoLongKan',
    'id restaurant': 624,
    'id chef': 'KL3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Arpège',
    'id restaurant': 626,
    'id chef': 'KL3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Folderol',
    'id restaurant': 417,
    'id chef': 'KL3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Rigmarole',
    'id restaurant': 313,
    'id chef': 'KL3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Tempilenti',
    'id restaurant': 331,
    'id chef': 'KL3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': "L'Osteria Dell'Anima",
    'id restaurant': 627,
    'id chef': 'KL3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Jixiao’s Buns',
    'id restaurant': 628,
    'id chef': 'KL3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Chez Magda',
    'id restaurant': 629,
    'id chef': 'KL3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Petit Vendôme',
    'id restaurant': 630,
    'id chef': 'KL3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Président',
    'id restaurant': 631,
    'id chef': 'KL3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Reyna',
    'id restaurant': 632,
    'id chef': 'KL3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Ze Kitchen Galerie',
    'id restaurant': 633,
    'id chef': 'KL3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': "Boutique yam'Tcha",
    'id restaurant': 634,
    'id chef': 'KL3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Semilla',
    'id restaurant': 635,
    'id chef': 'CC3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': "Freddy's",
    'id restaurant': 636,
    'id chef': 'CC3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Frenchie Bar a Vins',
    'id restaurant': 502,
    'id chef': 'CC3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Clamato',
    'id restaurant': 354,
    'id chef': 'CC3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Daroco Bourse',
    'id restaurant': 637,
    'id chef': 'CC3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Doyenné',
    'id restaurant': 312,
    'id chef': 'CC3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Restaurant des Jardins de Courances',
    'id restaurant': 638,
    'id chef': 'CC3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Relais Louis XIII',
    'id restaurant': 639,
    'id chef': 'DR3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Relais de l’entrecôte',
    'id restaurant': 640,
    'id chef': 'DR3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Tan Dinh',
    'id restaurant': 641,
    'id chef': 'DR3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Mardin Soupe - Çorba salonu',
    'id restaurant': 642,
    'id chef': 'DR3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Auberge Bressane',
    'id restaurant': 643,
    'id chef': 'DR3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Udon Bistro Kunitoraya',
    'id restaurant': 378,
    'id chef': 'DR3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Duc',
    'id restaurant': 644,
    'id chef': 'DR3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Bob de Tunis',
    'id restaurant': 453,
    'id chef': 'DR3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'La Boule Rouge',
    'id restaurant': 645,
    'id chef': 'DR3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Baron Rouge',
    'id restaurant': 646,
    'id chef': 'DR3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Baratin',
    'id restaurant': 325,
    'id chef': 'DR3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Au Petit Tonneau',
    'id restaurant': 647,
    'id chef': 'EF3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Tekés',
    'id restaurant': 648,
    'id chef': 'EF3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Homer Lobster',
    'id restaurant': 649,
    'id chef': 'EF3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': "La Tour D'Argent",
    'id restaurant': 650,
    'id chef': 'EF3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Au Pied de Cochon',
    'id restaurant': 651,
    'id chef': 'EF3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Doyenné',
    'id restaurant': 312,
    'id chef': 'EF3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Café des Ministères',
    'id restaurant': 330,
    'id chef': 'EF3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Bontemps',
    'id restaurant': 652,
    'id chef': 'EF3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Bristol',
    'id restaurant': 653,
    'id chef': 'EF3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Drugstore',
    'id restaurant': 654,
    'id chef': 'EF3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Brasserie Lazare',
    'id restaurant': 655,
    'id chef': 'EF3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Mermoz',
    'id restaurant': 656,
    'id chef': 'RT3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Kokoro Paris',
    'id restaurant': 657,
    'id chef': 'RT3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Amarante',
    'id restaurant': 658,
    'id chef': 'RT3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'La Cave à Michel',
    'id restaurant': 659,
    'id chef': 'RT3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Petit Célestin',
    'id restaurant': 345,
    'id chef': 'RT3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Christopher Coutanceau',
    'id restaurant': 660,
    'id chef': 'RT3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Pigeon Noir',
    'id restaurant': 1007,
    'id chef': 'RT3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Prado',
    'id restaurant': 1008,
    'id chef': 'RT3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Sepia',
    'id restaurant': 661,
    'id chef': 'RT3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'La Halle aux Grains',
    'id restaurant': 662,
    'id chef': 'RT3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Relais de Venise',
    'id restaurant': 663,
    'id chef': 'EVG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Verre Volé',
    'id restaurant': 359,
    'id chef': 'EVG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Amarante',
    'id restaurant': 658,
    'id chef': 'EVG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Ozlem',
    'id restaurant': 667,
    'id chef': 'EVG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Lao Siam',
    'id restaurant': 324,
    'id chef': 'EVG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Minh Chau',
    'id restaurant': 668,
    'id chef': 'EVG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'AT',
    'id restaurant': 669,
    'id chef': 'EVG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Sanjo',
    'id restaurant': 431,
    'id chef': 'EVG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Faggio',
    'id restaurant': 670,
    'id chef': 'EVG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Dreamin Man',
    'id restaurant': 671,
    'id chef': 'EVG3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Les Fines Gueules',
    'id restaurant': 672,
    'id chef': 'ACM3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Beaucé',
    'id restaurant': 673,
    'id chef': 'ACM3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Korus',
    'id restaurant': 674,
    'id chef': 'ACM3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Dilia la Cave',
    'id restaurant': 364,
    'id chef': 'ACM3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Parcelles',
    'id restaurant': 414,
    'id chef': 'ACM3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'La Halle aux Grains',
    'id restaurant': 662,
    'id chef': 'KO3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Septime',
    'id restaurant': 398,
    'id chef': 'KO3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'David Toutain',
    'id restaurant': 387,
    'id chef': 'KO3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Servan',
    'id restaurant': 675,
    'id chef': 'KO3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Arpège',
    'id restaurant': 356,
    'id chef': 'KO3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Frédéric Simonin',
    'id restaurant': 676,
    'id chef': 'KO3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Clarence',
    'id restaurant': 323,
    'id chef': 'KO3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Recoin',
    'id restaurant': 320,
    'id chef': 'TN3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Passerini',
    'id restaurant': 357,
    'id chef': 'TN3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Servan',
    'id restaurant': 675,
    'id chef': 'TN3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Racines',
    'id restaurant': 362,
    'id chef': 'TN3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Les Arlots',
    'id restaurant': 623,
    'id chef': 'TN3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Bouche',
    'id restaurant': 678,
    'id chef': 'TN3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Café les Deux Gares',
    'id restaurant': 344,
    'id chef': 'TN3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Pouliche',
    'id restaurant': 679,
    'id chef': 'KN3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Tempilenti',
    'id restaurant': 331,
    'id chef': 'KN3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Bel Ordinaire',
    'id restaurant': 680,
    'id chef': 'KN3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Korus',
    'id restaurant': 681,
    'id chef': 'KN3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Towa',
    'id restaurant': 682,
    'id chef': 'KN3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'F.I.E.F',
    'id restaurant': 683,
    'id chef': 'KN3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'HuThoPi',
    'id restaurant': 684,
    'id chef': 'KN3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Abri',
    'id restaurant': 677,
    'id chef': 'KN3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Clamato',
    'id restaurant': 354,
    'id chef': 'KN3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Chocho',
    'id restaurant': 685,
    'id chef': 'KN3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Le Mandarin',
    'id restaurant': 686,
    'id chef': 'MCC3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Song Heng',
    'id restaurant': 327,
    'id chef': 'MCC3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Lao Siam',
    'id restaurant': 324,
    'id chef': 'MCC3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'New Hoa Khoan',
    'id restaurant': 451,
    'id chef': 'MCC3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Urfa Durum',
    'id restaurant': 337,
    'id chef': 'MCC3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Ravioli nord est',
    'id restaurant': 687,
    'id chef': 'MCC3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Ntaba Chikwange Sandwicherie',
    'id restaurant': 688,
    'id chef': 'MCC3',
    Review: '',
    'Best dish': '',
  },
  {
    'restaurant name': 'Restaurant Les délices de Tunisie',
    'id restaurant': 689,
    'id chef': 'MCC3',
    Review: '',
    'Best dish': '',
  },
];

const reviewSlice = createSlice({
  name: 'review',
  initialState: initailReviews,
  reducers: {
    fetchAllReviews: (
      state,
      action: PayloadAction<{ initialReviews: any[] }>,
    ) => {
      return action.payload.initialReviews;
    },
  },
});

export const { fetchAllReviews } = reviewSlice.actions;
export default reviewSlice.reducer;
