import { createSlice, PayloadAction } from '@reduxjs/toolkit';

const initialChefs = [
  {
    id: 'EX: 786969',
    name: 'Robert Mendoza',
    overall_category: 'Europe',
    zone_category: 'France',
    zone_name: 'Paris',
    main_restaurant: 211,
    other_restaurants: '233,245',
  },
  {
    id: 'JC1',
    name: 'Jeffrey Claudio',
    overall_category: 'Europe',
    zone_category: 'Germany',
    zone_name: 'Berlin',
    main_restaurant: 100,
    other_restaurants: '-',
  },
  {
    id: 'DR1',
    name: 'Daniel Remers',
    overall_category: 'Europe',
    zone_category: 'Germany',
    zone_name: 'Berlin',
    main_restaurant: 146,
    other_restaurants: '-',
  },
  {
    id: 'MG2',
    name: 'Mario Gamba',
    overall_category: 'Europe',
    zone_category: 'Germany',
    zone_name: 'Munich',
    main_restaurant: 101,
    other_restaurants: '-',
  },
  {
    id: 'RM3',
    name: 'Robert Mendoza',
    overall_category: 'Europe',
    zone_category: 'France',
    zone_name: 'Paris',
    main_restaurant: 'x',
    other_restaurants: '',
  },
  {
    id: 'BG3',
    name: 'Bertrand Grebaux',
    overall_category: 'Europe',
    zone_category: 'France',
    zone_name: 'Paris',
    main_restaurant: 301,
    other_restaurants: '-',
  },
  {
    id: 'MG3',
    name: 'Michael Grosman',
    overall_category: 'Europe',
    zone_category: 'France',
    zone_name: 'Paris',
    main_restaurant: 302,
    other_restaurants: '',
  },
  {
    id: 'GS3',
    name: 'Guillaume Sanchez',
    overall_category: 'Europe',
    zone_category: 'France',
    zone_name: 'Paris',
    main_restaurant: '',
    other_restaurants: '',
  },
  {
    id: 'GP3',
    name: 'Giovanni Passerini',
    overall_category: 'Europe',
    zone_category: 'France',
    zone_name: 'Paris',
    main_restaurant: 357,
    other_restaurants: '',
  },
  {
    id: 'EC3',
    name: 'Enrique Casarrubias',
    overall_category: 'Europe',
    zone_category: 'France',
    zone_name: 'Paris',
    main_restaurant: 308,
    other_restaurants: '',
  },
  {
    id: 'HG3',
    name: 'Hanz Gueco',
    overall_category: 'Europe',
    zone_category: 'France',
    zone_name: 'Paris',
    main_restaurant: 303,
    other_restaurants: '',
  },
  {
    id: 'AS3',
    name: 'Amandine Sepulcre',
    overall_category: 'Europe',
    zone_category: 'France',
    zone_name: 'Paris',
    main_restaurant: 'x',
    other_restaurants: '',
  },
  {
    id: 'MS3',
    name: 'Mory Sacko',
    overall_category: 'Europe',
    zone_category: 'France',
    zone_name: 'Paris',
    main_restaurant: 304,
    other_restaurants: 504,
  },
  {
    id: 'ST3',
    name: 'Simone Tondo',
    overall_category: 'Europe',
    zone_category: 'France',
    zone_name: 'Paris',
    main_restaurant: 362,
    other_restaurants: '',
  },
  {
    id: 'TC3',
    name: 'Thomas Coupeau',
    overall_category: 'Europe',
    zone_category: 'France',
    zone_name: 'Paris',
    main_restaurant: 'x',
    other_restaurants: '',
  },
  {
    id: 'NGE3',
    name: 'Noam Gedalof & Etheliya Hananova',
    overall_category: 'Europe',
    zone_category: 'France',
    zone_name: 'Paris',
    main_restaurant: 305,
    other_restaurants: '',
  },
  {
    id: 'AG3',
    name: 'Alan Geaam',
    overall_category: 'Europe',
    zone_category: 'France',
    zone_name: 'Paris',
    main_restaurant: 306,
    other_restaurants: '',
  },
  {
    id: 'MG33',
    name: 'Mathieu Grichois',
    overall_category: 'Europe',
    zone_category: 'France',
    zone_name: 'Paris',
    main_restaurant: 307,
    other_restaurants: '',
  },
  {
    id: 'TM3',
    name: 'Tom Meyer',
    overall_category: 'Europe',
    zone_category: 'France',
    zone_name: 'Paris',
    main_restaurant: 309,
    other_restaurants: '',
  },
  {
    id: 'SM3',
    name: 'Sho Miyashita',
    overall_category: 'Europe',
    zone_category: 'France',
    zone_name: 'Paris',
    main_restaurant: 310,
    other_restaurants: '',
  },
  {
    id: 'HC3',
    name: 'Hugh Corcoran',
    overall_category: 'Europe',
    zone_category: 'France',
    zone_name: 'Paris',
    main_restaurant: 311,
    other_restaurants: '',
  },
  {
    id: 'GM3',
    name: 'Gregory Marchand',
    overall_category: 'Europe',
    zone_category: 'France',
    zone_name: 'Paris',
    main_restaurant: 501,
    other_restaurants: '502,503,372',
  },
  {
    id: 'CVF3',
    name: 'Clement Vergeat and Félix Bogniard',
    overall_category: 'Europe',
    zone_category: 'France',
    zone_name: 'Paris',
    main_restaurant: 601,
    other_restaurants: '',
  },
  {
    id: 'JG3',
    name: 'Jason Gouzy',
    overall_category: 'Europe',
    zone_category: 'France',
    zone_name: 'Paris',
    main_restaurant: 602,
    other_restaurants: '',
  },
  {
    id: 'MI3',
    name: 'Masahide Ikuta',
    overall_category: 'Europe',
    zone_category: 'France',
    zone_name: 'Paris',
    main_restaurant: 603,
    other_restaurants: '',
  },
  {
    id: 'KL3',
    name: 'Khan - ly Huynh',
    overall_category: 'Europe',
    zone_category: 'France',
    zone_name: 'Paris',
    main_restaurant: 604,
    other_restaurants: '',
  },
  {
    id: 'CC3',
    name: 'Charles Compagnon',
    overall_category: 'Europe',
    zone_category: 'France',
    zone_name: 'Paris',
    main_restaurant: 605,
    other_restaurants: 611,
  },
  {
    id: 'DR3',
    name: 'Daniel Rose',
    overall_category: 'Europe',
    zone_category: 'France',
    zone_name: 'Paris',
    main_restaurant: 701,
    other_restaurants: 1006,
  },
  {
    id: 'EF3',
    name: 'Eric Frechon',
    overall_category: 'Europe',
    zone_category: 'France',
    zone_name: 'Paris',
    main_restaurant: 653,
    other_restaurants: '654,655',
  },
  {
    id: 'RT3',
    name: 'Romain Thibault',
    overall_category: 'Europe',
    zone_category: 'France',
    zone_name: 'Paris',
    main_restaurant: 608,
    other_restaurants: '',
  },
  {
    id: 'EVG3',
    name: 'Édouard Vermynck & Geoffroy Langella',
    overall_category: 'Europe',
    zone_category: 'France',
    zone_name: 'Paris',
    main_restaurant: 609,
    other_restaurants: '',
  },
  {
    id: 'ACM3',
    name: 'Anthony Chouchan et Matthieu Hernandez',
    overall_category: 'Europe',
    zone_category: 'France',
    zone_name: 'Paris',
    main_restaurant: 610,
    other_restaurants: '',
  },
  {
    id: 'KO3',
    name: 'Katsu Okiyama',
    overall_category: 'Europe',
    zone_category: 'France',
    zone_name: 'Paris',
    main_restaurant: 677,
    other_restaurants: 397,
  },
  {
    id: 'TN3',
    name: 'Tamir Nahmias',
    overall_category: 'Europe',
    zone_category: 'France',
    zone_name: 'Paris',
    main_restaurant: 366,
    other_restaurants: '',
  },
  {
    id: 'KN3',
    name: 'Kosuke Nabeta',
    overall_category: 'Europe',
    zone_category: 'France',
    zone_name: 'Paris',
    main_restaurant: 703,
    other_restaurants: '',
  },
  {
    id: 'MCC3',
    name: 'Mads Christensen & Carlos Peñarredonda',
    overall_category: 'Europe',
    zone_category: 'France',
    zone_name: 'Paris',
    main_restaurant: 380,
    other_restaurants: '',
  },
];
const chefsSlice = createSlice({
  name: 'chefs',
  initialState: initialChefs,
  reducers: {
    fetchAllChefs: (state, action: PayloadAction<{ initialChefs: any[] }>) => {
      return action.payload.initialChefs;
    },
  },
});

export const { fetchAllChefs } = chefsSlice.actions;
export default chefsSlice.reducer;
